name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Build and Push
        run: |
          python3 perfzero/lib/setup.py --dockerfile_path=docker/Dockerfile_ubuntu_2204_tf_cuda_12 --docker_tag=ghcr.io/ironbeer/benchmarks:latest
          docker images
          docker push ghcr.io/ironbeer/benchmarks:latest
